build-by-default: true
branches:
- main
projects:
  Remark:
    path: ""
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
      - src: sof3/await-generator/await-generator
        version: ^3.3.0
        epitope: .random
...
